In [ ]:
#time the cells 



from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV


#from xgboost import XGBClassifier
from sklearn import model_selection
from sklearn.utils import class_weight

import numpy as np
import pandas as pd



data = pd.read_csv('Train_clean.csv')

In [ ]:
data.head()


Unnamed: 0  Survived  Pclass  Sex  Age  SibSp  Parch      Fare  Embarked  \
0           0         0       3    1    2      1      0 -0.502445         2   
1           1         1       1    0    5      1      0  0.786845         0   
2           2         1       3    0    3      0      0 -0.488854         2   
3           3         1       1    0    5      1      0  0.420730         2   
4           4         0       3    1    5      0      0 -0.486337         2   

   Deck  relatives  not_alone  Title  
0     7          1          0      1  
1     2          1          0      3  
2     7          0          1      2  
3     2          1          0      3  
4     7          0          1      1

In [ ]:
X = data.drop(columns=['Survived', "Unnamed: 0"], axis=1)
y = data.Survived
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state=0)


In [ ]:
  models = [
          ('LogReg', LogisticRegression()), 
          ('RF', RandomForestClassifier()),
          ('KNN', KNeighborsClassifier()),
          ('SVM', SVC()), 
          ('GNB', GaussianNB())
        
        ]

In [ ]:
data2 = pd.read_csv('Test_clean.csv') 
data2.head()

X2 = data.drop(columns=['Survived', "Unnamed: 0"], axis=1)
# no Y?



In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
X2 = scaler.fit_transform(X2)








In [ ]:
def moreinfo(x):
    print(confusion_matrix(y_test,y_prediction))
    print(classification_report(y_test,y_prediction))
    accScoreTest = accuracy_score(y_train,x.predict(X_train))
    accScoreTrain = accuracy_score(y_test,x.predict(X_test))


    #setattr(x,'title', value)
    #getattr(x,title) or x.title


In [ ]:
for kernel in ('sigmoid','poly','rbf', 'linear'):
        svclassifier = SVC(kernel=kernel)
        sv = svclassifier.fit(X_train, y_train)
        # print(sv.score(X_train, y_train))
        y_prediction = svclassifier.predict(X_test)
      
        print(accuracy_score(y_test, y_prediction))

        y_prediction = sv.predict(X2)
      

       


0.6974789915966386
0.8179271708683473
0.8207282913165266
0.7927170868347339


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C':[0.1, 1, 10, 100], 'gamma': [1,0.1,0.01,0.001], 'kernel': ['rbf', 'poly', 'sigmoid']}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=5)

y = y_train
y = y.values.ravel()
grid.fit(X_train, y)

In [ ]:
def QuickScores():
    scores= []

    for kernel in ('sigmoid','poly','rbf', 'linear'):
        svclassifier = SVC(kernel=kernel)
        sv = svclassifier.fit(X_train, y_train)
        # print(sv.score(X_train, y_train))
        y_prediction = svclassifier.predict(X_test)

        #this should be its own functoin
        # print(confusion_matrix(y_test,y_prediction))
        # print(classification_report(y_test,y_prediction))
        # get the accuracy
        score = (X_test,y_test) 
        scores = scores.append(score)


    lor = LogisticRegression()
    lor.fit(X_train,y_train)
    score = lor.score(X_test, y_test)
    print(score)
    scores = scores.append(score)

    lr = LinearRegression()
    lr.fit(X_train,y_train)
    lr.score(X_test, y_test)
    scores = scores.append(score)

    rf = RandomForestClassifier()
    rf.fit(X_train,y_train)
    rf.score(X_test, y_test)
    scores = scores.append(score)


    kn = KNeighborsClassifier()
    kn.fit(X_train, y_train)
    kn.score(X_test, y_test)
    scores = scores.append(score)

    gb = GaussianNB()
    gb.fit(X_train, y_train)
    gb.score(X_test, y_test)
    scores = scores.append()

    gbr = GradientBoostingRegressor(random_state=0)
    gbr.fit(X_train, y_train)
    gbr.score(X_test, y_test)
    scores = scores.append()

    

    pca = PCA(n_components=8)
    pca.fit(X_train, y_train)
    pca.score(X, y)
    scores = scores.append()





In [ ]:

def moreinfo(x):
    print(confusion_matrix(y_test,y_prediction))
    print(classification_report(y_test,y_prediction))
    accScoreTest = accuracy_score(y_train,x.predict(X_train))
    accScoreTrain = accuracy_score(y_test,x.predict(X_test))
    print("Training accuracy =",accScoreTest)
    print("Validation accuracy =",accScoreTrain)
    check = (accScoreTest/accScoreTrain)
    if (0.90 > check > 1.1):
        print ('Warning!! Value may suggest overfitting -->',check)
    else:
        print('Everything looks okay, explore further ---> ',check)

   
lor = LogisticRegression()
lor.fit(X_train,y_train)
score = lor.score(X_test, y_test)
print(score)

y_prediction = lor.predict(X_test)
y_prediction


moreinfo(lor)



0.7955182072829131
[[185  36]
 [ 37  99]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       221
           1       0.73      0.73      0.73       136

    accuracy                           0.80       357
   macro avg       0.78      0.78      0.78       357
weighted avg       0.80      0.80      0.80       357

Training accuracy = 0.8277153558052435
Validation accuracy = 0.7955182072829131
Everything looks okay, explore further --->  1.0404731761354646


In [ ]:
lr = LinearRegression()
lr.fit(X_train,y_train)
print(lr.score(X_test, y_test))

y_prediction = lr.predict(X2)
y_prediction


0.3821455447971983


array([ 0.13375833,  1.00109425,  0.61149625,  0.91603183,  0.0502937 ,
        0.11298496,  0.27302687,  0.27971527,  0.69635752,  0.96211016,
        0.65303442,  0.76876323,  0.12811058, -0.17749948,  0.66332705,
        0.74390972,  0.24271535,  0.18690325,  0.69592256,  0.75553259,
        0.169616  ,  0.16731313,  0.69992408,  0.32036411,  0.49668304,
        0.42946323,  0.14864474,  0.26920495,  0.62200738,  0.07613004,
        0.74101871,  1.0786922 ,  0.6219214 ,  0.13336154,  0.41945512,
        0.27453691,  0.14864754,  0.12811058,  0.59742152,  0.74472279,
        0.66431007,  0.83123435,  0.14909117,  0.79845614,  0.6738853 ,
        0.07623266,  0.12385149,  0.6219214 ,  0.08560652,  0.77360633,
        0.2132643 ,  0.1279442 ,  0.97719242,  0.80862297,  0.39261453,
        0.31718969,  0.7465252 ,  0.14864754,  0.71629145,  0.08934044,
        0.20052545,  0.83186125,  0.30342009,  0.23437143,  0.37703759,
        0.40271694,  0.79530172,  0.12818265,  0.33326865,  0.02

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
print(rf.score(X_test, y_test))

y_prediction = rf.predict(X2)
y_prediction


0.8067226890756303


array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,

In [ ]:
kn = KNeighborsClassifier()
kn.fit(X_train, y_train)
io = (kn.score(X_test, y_test))
print(io)

y_prediction = kn.predict(X2)
y_prediction



0.8403361344537815


array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [ ]:
gb = GaussianNB()
gb.fit(X_train, y_train)
print(gb.score(X_test, y_test))

y_prediction = gb.predict(X2)
y_prediction

NameError: name 'GaussianNB' is not defined

In [ ]:
gbr = GradientBoostingRegressor()
gbr.fit(X_train, y_train)
print(gbr.score(X_test, y_test))

y_prediction = gbr.predict(X2)
y_prediction

In [ ]:
pca = PCA(n_components=8)
pca.fit(X_train, y_train)
print(pca.score(X, y))

y_prediction = pca.predict(X2)
y_prediction

-66.47356452312549


AttributeError: 'PCA' object has no attribute 'predict'

In [ ]:
kmeans = KMeans()
kmeans.fit(X)


In [ ]:
test_final = pd.read_csv('Test_clean.csv')
test_final.drop(columns=['Unnamed: 0', 'Name'], inplace=True, axis=1)

test_final['Fare'].fillna(0, inplace=True)

In [ ]:
gbc_pred = gbc.predict(test_final)
gbc_pred.sum()

85

In [ ]:
ID = pd.read_csv('test.csv')
ID = ID['PassengerId']


In [ ]:
from sklearn.ensemble import GradientBoostingCla

GradientBoostingClassifier()

In [ ]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)

GradientBoostingClassifier()

In [ ]:
gbc_pred = gbc.predict(test_final)

In [ ]:
ds = pd.DataFrame(ID, rf_pred)

In [ ]:
ds.s

PassengerId
0           892
0           892
0           892
0           892
0           892
..          ...
0           892
0           892
0           892
0           892
0           892

[418 rows x 1 columns]

0    19
dtype: int64

In [ ]:
test_final.head()

Unnamed: 0  Pclass  Sex  Age  SibSp  Parch      Fare  Embarked Deck  \
0           0       3    1    5      0      0 -0.497811         1    M   
1           1       3    0    6      1      0 -0.512660         2    M   
2           2       2    1    6      0      0 -0.464532         1    M   
3           3       3    1    3      0      0 -0.482888         2    M   
4           4       3    0    2      1      1 -0.417971         2    M   

   relatives  Title  
0          0      1  
1          1      3  
2          0      1  
3          0      1  
4          2      3

In [ ]:
test_final = pd.read_csv('Test_clean.csv', index_col=0)
test_final.drop('Name', axis=1, inplace=True)

In [ ]:
test_final.fillna(0, inplace=True)

In [ ]:
test_final['Fare'].fillna(0, inplace=True)

In [ ]:
rf.predict(test_final)

ValueError: X has 10 features, but DecisionTreeClassifier is expecting 11 features as input.

In [ ]:
test_final['Fare'].fillna(0, inplace=True)


In [ ]:
pred = kn.predict(test_final)

In [ ]:
X_train.drop('relatives', axis=1, inplace=True)


Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Deck',
       'relatives', 'not_alone', 'Title'],
      dtype='object')

In [ ]:
Take a look on top!!!! I have something CELL 140

In [ ]:
test_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Pclass     418 non-null    int64  
 1   Sex        418 non-null    int64  
 2   Age        418 non-null    int64  
 3   SibSp      418 non-null    int64  
 4   Parch      418 non-null    int64  
 5   Fare       418 non-null    float64
 6   Embarked   418 non-null    int64  
 7   Deck       418 non-null    int64  
 8   relatives  418 non-null    int64  
 9   Title      418 non-null    int64  
dtypes: float64(1), int64(9)
memory usage: 52.1 KB


In [ ]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
sub = pd.DataFrame({'PassengerId': ID, 'Survived':gbc_pred })

In [ ]:
sub.to_csv('submission.csv')

In [ ]:
sub.to_csv('submission.csv', index=False)

In [ ]:
submission.to_csv('submission.csv')

In [ ]:
submission = submission.rename(columns={0:'Survived'})

In [ ]:
submission.to_csv('submission.csv', index=False)

In [ ]:
submission

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [ ]:
knn = KNeighborsClassifier()
knn.fit(X, y)

ValueError: Found input variables with inconsistent numbers of samples: [891, 534]

In [ ]:
knn.predict(test_final).sum()

32

In [ ]:
knn_pred = knn.predict(test_final)

In [ ]:
sub = pd.DataFrame({'PassengerId': ID, 'Survived':knn_pred })

In [ ]:
sub.to_csv('submission.csv', index=False)

In [ ]:
submit = y_prediction

AttributeError: module 'pandas' has no attribute 'Dataframe'

![Picture title](image-20210129-174814.png)

y![Picture title](image-20210129-174723.png)

![Picture title](image-20210129-174719.png)

In [ ]:
knn

KNeighborsClassifier()